# Generated by Django 5.0 on 2023-12-22 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('pagado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=240)),
                ('fechaHora', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='evento.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='evento.evento')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='evento.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historialPrecios', to='evento.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=240)),
                ('apellido', models.CharField(max_length=240)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incriptos', to='evento.estado')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptos', to='evento.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateTimeField(auto_now=True)),
                ('pago', models.CharField(blank=True, max_length=80)),
                ('qr', models.CharField(max_length=80)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evento_inscriptos', to='evento.evento')),
                ('inscripto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evento_inscriptos', to='evento.inscripto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInscripto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalleInscriptos', to='evento.grupo')),
                ('inscripto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalleInscriptos', to='evento.inscripto')),
            ],
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='evento.estado')),
                ('inscripto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='evento.inscripto')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provincias', to='evento.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigoPostal', models.IntegerField()),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localidades', to='evento.provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=150)),
                ('nro', models.IntegerField()),
                ('coordenada', models.CharField(blank=True, max_length=80)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones', to='evento.localidad')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='evento.ubicacion'),
        ),
    ]
