# Generated by Django 5.0 on 2023-12-14 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=240)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='evento.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Incripto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=240)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incriptos', to='evento.estado')),
            ],
        ),
    ]
