# Generated by Django 5.0 on 2023-12-22 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='estado',
            name='tipoEstado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='evento.tipoestado'),
            preserve_default=False,
        ),
    ]
