# Generated by Django 5.0 on 2023-12-14 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=240)),
                ('apellido', models.CharField(max_length=240)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incriptos', to='evento.estado')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptos', to='evento.evento')),
            ],
        ),
        migrations.DeleteModel(
            name='Incripto',
        ),
    ]
