# Generated by Django 5.0 on 2023-12-22 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_tipoestado_estado_tipoestado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detalle_Evento',
            new_name='DetalleEvento',
        ),
    ]
